language: node_js
node_js: '8'
deploy:
  provider: npm
  email: sparrow.jang@gmail.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: ATbx0IY+hDCEHmfMpVTUJhrAcgASBFEBH87F1o5cPLnvSdpk8nvAcWOpaD3fPIJfFQ1Ee28HOlcmPWeii0VJCvM0SFgq4lEykHrj7EkdU9Lli6JafIGxf1qQi9NCDhCeIp5GfsfNtgtKJrZJx+6ON1zhp+shaHyEznyI/cHbpTsxJhywldwMxMhBLuIPzCI4hT9g5paK6Vw3QaWp1lsW+kKhapprYTqweVoIA+6GBSdDyZ9lrdAE7JP4g5PCGrejv5LS7MHCf5/V2KqpjGKdHrj4BeyotdZ1tvO6ywGVSu0epAzHCX6jkse/ZWWVb4pLIgilzNHNHHVhZkpAqvEeIcHBwFe0s9UeI+hIIOqlpqMIN2Allp8V04rj9q5+I9nqUQ9mkVA9eC70PR5XBYBsGi8LEUmDSyAiMWJ0EAGP6yAWd3umzMc5JQnxrWSg0oP2HMVHbCtGylJUG30tgsy35CMveqhCRQYmrZWo4cwem3fH4KTj9WybiEhCtWIzmgJJq7r0MAKLvOPZ59n8UJMAiuvdT5+bVIM+Nf3sFApfuxzBGo0YqEfpKIFlWtrNS6hg6J6GOi0DivA1Wx9dcj9yUc8uToB8Qzwy5TRErP+fD+ixgbSTUqX7/vlORD3rxdFosWWY3hZ7Ymel56LiBQTueh6vCQ65ufial7QT35kN84M=
